config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users
  
  root "users#home"
  get 'tags/:tag', to: 'recipes#index', as: :tag
  

  resources :recipes do
    put :like, on: :member
    put :favorite, on: :member  
  end
  resources :favorite_recipes,       only: [:create, :destroy]
  resources :categories
end    

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  acts_as_taggable
  acts_as_votable
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
  belongs_to :user
  belongs_to :category
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 } 
  validates :ingredients, presence: true, length: { maximum: 2000 } 
  validates :method, presence: true, length: { maximum: 10000 } 
  validate :picture_size
  validates :category_id, presence: true

  
  validate :validates_progression

  def validates_progression
     true # stub
  end



  def liked_by_user?(user)
    get_likes.where(voter_id: user).count > 0
  end
  
  def favorited_by?(other_user)
    favorited_by.include?(other_user)
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less then 5MB")
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  require 'will_paginate/array'
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy


  def like
    @recipe = Recipe.find(params[:id])
    type = params[:type]
    if type == "like"
      @recipe.liked_by current_user
      flash[:success] = "You liked #{@recipe.name}"
      respond_to do |format|
        format.html 
        format.js 
      end
    elsif type == "unlike"
      @recipe = Recipe.find(params[:id])
      @recipe.unliked_by current_user
      flash[:danger] = "Unliked #{@recipe.name}"
      respond_to do |format|
        format.html 
        format.js 
      end
  else
    redirect_to :back
    flash[:info] = 'Nothing happened.'
  end
end
  
  def favorite
     @recipe = Recipe.find(params[:id])
     
      type = params[:type]
      if type == "favorite"
        favorite_recipe = current_user.favorite_recipes.build(recipe_id: params[:id])
        favorite_recipe.save
        
        flash[:success] = "You favorited #{@recipe.name}"
          respond_to do |format|
          format.html 
          format.js
        end

      elsif type == "unfavorite"
        current_user.favorites.delete(@recipe)
        
        flash[:danger] = "Unfavorited #{@recipe.name}"
        respond_to do |format|
          format.html 
          format.js
        end

      else
        redirect_to :back
        flash[:info] = 'Nothing happened.'
      end
    end
    
    
  #   if params[:type] == "favorite"
  #     @recipe = Recipe.find(params[:id])
  #     @recipes = current_user.favorites.build
  #     # puts "============================#{@recipe.inspect}"
  #     @recipes.save
  #     # recipe = @recipe.update_attributes(params[:id])

  #     redirect_to :back, notice: 'You Favorited #{@recipe.name}'

  #   elsif type == "unfavorite"
  #     current_user.favorite_recipes.delete(@recipe)
  #     redirect_to :back, notice: 'Unfavorited #{@recipe.name}'

  #   else
  #     redirect_to :back, notice: 'Nothing happened.'
  #   end
  # end


  def index
    if params[:r].present?
      @recipes = Recipe.where('name like ?', "%#{params[:r]}%").paginate(page: params[:page], per_page: 1)
    elsif params[:tag].present?
      @recipes = Recipe.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 1)
    else
      @recipes = Recipe.all.paginate(page: params[:page], per_page: 1)
    end
    @categories = Category.all
    @favorite_recipe = current_user.favorites
  end

  
  def new
    @recipe = Recipe.new
  end

  def create 
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe created!"
      redirect_to root_url
    else  
      flash[:danger] = "Fill All field"
      render "new"
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted"
    redirect_to request.referrer || user_path(current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @like_recipe = current_user.find_liked_items.paginate(page: params[:page], per_page: 1)
    
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      flash[:success] = "profile Updated"
      redirect_to @recipe
      #handle a successful update. 
    else
      render 'edit'
    end
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :category_id, :ingredients, :method, :tag_list, :picture)
    end

    def correct_user
      @recipe = current_user.recipes.find_by(id: params[:id])
      redirect_to root_url if @recipe.nil?
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def get_voter_name(recipe)
    recipe.votes_for.up.by_type(User).voters.map{ |voter| voter.name }.join(', ')
  end

end

app/views/recipes/_favorite_btn.html.erb
<% type = recipe.favorited_by.include?(current_user) ? 'unfavorite' : 'favorite'  %>
<%= link_to type, favorite_recipe_path(recipe, type: type), method: :put, class: "btn btn-primary", remote: true %>

app/views/recipes/_like.html.erb
<% type = recipe.liked_by_user?(current_user) ? 'unlike' : 'like' %>
<%= link_to type, like_recipe_path(recipe, type: type), method: :put, class: "btn btn-primary", remote: true %>

<span class="heart-no" data-id="<%= recipe.id %>"><%= recipe.get_likes.size %></span>

      

app/views/recipes/_recipe.html.erb
<div class = "detail" id="recipe-<%= recipe.id %>">
	<li style = "font-size: 20px"><%= link_to recipe.name, recipe_path(recipe) %></li>
	<% if recipe.picture? %>
    	<li><%= link_to image_tag(recipe.picture.url, size: '200x200'), recipe_path(recipe)  %></li>
    <% end %>
    <li>Tags: <%= raw recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></li>
	<li><span class="timestamp">
	    Posted <%= time_ago_in_words(recipe.created_at) %> ago.
	    <% if (recipe.user_id == current_user.id)  %>
		    <%= link_to "delete  ", recipe, method: :delete, data: {confirm: "You sure?"} %>| <%= link_to " Edit", edit_recipe_path(recipe) %>
	    <% elsif recipe.user_id != current_user.id %>
	      	<div id='favorite'>
   		 		<%= render partial: "recipes/favorite_btn", locals: {recipe: recipe} %>
   		  	</div>
	    <% end %>
   		<br> 
		    <div id = 'like'>
		  		<%= render partial: "recipes/like", locals: {recipe: recipe} %> 
		  	</div> 
   	    </span>
	</li>
</div>
<br>
  

app/views/recipes/edit.html.erb
<%= form_for(@recipe, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
	<%= f.label :recipe_name %>
	<%= f.text_field :name, class: 'form-control'%>

	<%= f.label :category %>
	<%= f.collection_select(:category_id , Category.all, :id, :name) %>

	<%= f.label :ingredients %>
	<%= f.text_area :ingredients, class: 'form-control' %>

	<%= f.label :method %>
	<%= f.text_area :method, class: 'form-control' %>

	<%= f.label :tag_list, "Tags (separated by commas)" %>
	<%= f.text_field :tag_list, class: 'form-control' %>
	
	<span class = "picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <%= f.submit "Update Your Profile", class: "btn btn-primary"  %>
  </div>
  
<% end %>

app/views/recipes/favorite.js.erb
$('#favorite').html('<%= escape_javascript(render partial: "favorite_btn", locals: { recipe: @recipe })%>')

app/views/recipes/index.html.erb
<div class = "row">
  <%= render "shared/search" %>
</div>

<div class = "row">
  <div class = "col-sm-3">
    <h4><%= render 'categories/category' %></h4> 
    <div class = "well well-sm">
    <div id="tag_cloud well">
      <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="205">
        <li class="label label-info col-sm-12"><h5>Search Recipe from Following Tags</h5>
        </li>
      </ul>
    </div>
    <br>
      <% tag_cloud Recipe.tag_counts, %w[s m l] do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div> 
  </div>

  <div class="col-md-8 pull-right">
    <h3>All Recipes (<%= @recipes.count %>)</h3>
      <%= will_paginate @recipes %>
        <ul style = "list-style-type: none;">
          <%= render @recipes %>
        </ul>
      <%= will_paginate @recipes %>
  </div> 
</div>

app/views/recipes/like.js.erb
$('#like').html('<%= escape_javascript(render partial: "like", locals: { recipe: @recipe })%>')

app/views/recipes/new.html.erb
<div class="row">
<aside class="col-md-4">
<section class = "recipe_form">
<%= render 'shared/recipe_form' %>
</section>
</aside>
</div>

app/views/recipes/show.html.erb
<% provide(:title) %>

<div class="row">
  <div class="col-md-6">
    <% if @recipe %>
      
      <ul style = "list-style-type: none;">
		  <li style = "list-style-type: disc;"><big> Category : </big><%= @recipe.category.name %></li>
		  <li><big> Recipe Name : </big><%= @recipe.name %></li>
		  <li><%= image_tag @recipe.picture.url if @recipe.picture? %></li>
		  <li><big> Ingredients : </big><%= @recipe.ingredients %></li>
		  <li><big> Method : </big><%= @recipe.method %></li>
      </ul>
    <% end %>
  </div>

  <div class="col-md-6">
    <% if @like_recipe %>
      <table class = "table">
      <tr>
      <th>Recipe Name</th>
      <th>Liked User</th>
      </tr>
      <tr>
        <td><%= @recipe.name %></td>
        <td><%= get_voter_name(@recipe) %></td>
      </tr>
      </table>
    <% end %>
  </div>


</div>