config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users
  
  root "users#home"
  get 'tags/:tag', to: 'recipes#index', as: :tag
  

  resources :recipes do
    put :like, on: :member
    put :favorite, on: :member  
  end
  resources :favorite_recipes,       only: [:create, :destroy]
  resources :categories
end    

app/views/shared/_error_messages.html.erb
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@recipe.errors.count, "error") %>.
    </div>
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favorite_recipe.html.erb
	<li style = "font-size: 20px"><%= link_to recipe.name, recipe_path(recipe) %></li>
	<% if recipe.picture? %>
    	<li><%= link_to image_tag(recipe.picture.url, size: '200x200'), recipe_path(recipe)  %></li>
    <% end %>
    <li>Tags: <%= raw recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></li>
	<li><span class="timestamp">
	    Posted <%= time_ago_in_words(recipe.created_at) %> ago.</span></li>

app/views/shared/_marquee.html.erb
<% recipes.each do |recipe| %>
<li style = "font-size: 20px"><%= link_to recipe.name, recipe_path(recipe) %></li>
<% if recipe.picture? %>
	<li><%= link_to image_tag(recipe.picture.url, size: '200x200'), recipe_path(recipe)  %></li>
<% end %>
<li><span class="timestamp">
    Posted <%= time_ago_in_words(recipe.created_at) %> ago.</span></li>
    <% end %>

app/views/shared/_recipe.html.erb
  <li style = "list-style-type: disc;"><big> Category : </big><%= recipe.category.name %></li>
  <li><big> Recipe Name : </big><%= recipe.name %></li>
  <li><%= image_tag recipe.picture.url if recipe.picture? %></li>
  <li><big> Ingredients : </big><%= recipe.ingredients %></li>
  <li><big> Method : </big><%= recipe.method %></li>
  <br>
 

    

app/views/shared/_recipe_form.html.erb
<%= form_for(@recipe, html: { multipart: true }) do |f| %>
  <div class="field">
  <%= render "/shared/error_messages" %>
	<%= f.label :recipe_name %>
	<%= f.text_field :name, class: 'form-control'%>
    <%= f.label :category %>
	<%= f.collection_select(:category_id , Category.all, :id, :name,prompt: true) %>

	<%= f.label :ingredients %>
	<%= f.text_area :ingredients, class: 'form-control' %>

	<%= f.label :method %>
	<%= f.text_area :method, class: 'form-control' %>

	<%= f.label :tag_list, "Tags (separated by commas)" %>
	<%= f.text_field :tag_list, class: 'form-control' %>

	<span class = "picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <%= f.submit "Post", class: "btn btn-primary"  %>
  </div> 
<% end %>

<script type="text/javascript">
$('#recipe_picture').bind('change', function(){
	var size_in_megabytes = this.files[0].size/1024/1024;
	if (size_in_megabytes > 1) {
		alert('Maximum file size is 5MB, Please choose a smaller file.')
	}
});
</script>

app/views/shared/_search.html.erb
<%= form_tag recipes_path, method: :get do %>
<%= button_tag(type: 'submit', class: "btn btn-info pull-right") do %>
	  <span class="glyphicon glyphicon-search"></span> 
	  <% end %>
	 <div class= "col-lg-4 pull-right">
	  <%= text_field_tag :r %>
	</div>
	  
<% end %>